/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HydroRouteImport } from './routes/hydro'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiAccuweatherRouteImport } from './routes/api/accuweather'
import { Route as ApiAladinRouteImport } from './routes/api/aladin'
import { Route as ApiAviationRouteImport } from './routes/api/aviation'
import { Route as ApiBmkgRouteImport } from './routes/api/bmkg'
import { Route as ApiChmiRouteImport } from './routes/api/chmi'
import { Route as ApiChmiAqiRouteImport } from './routes/api/chmi-aqi'
import { Route as ApiChmiRadarRouteImport } from './routes/api/chmi-radar'
import { Route as ApiFmiRouteImport } from './routes/api/fmi'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiGeosphereRouteImport } from './routes/api/geosphere'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiHomeRouteImport } from './routes/api/home'
import { Route as ApiHydroRouteImport } from './routes/api/hydro'
import { Route as ApiImgwRouteImport } from './routes/api/imgw'
import { Route as ApiInpocasiStationsRouteImport } from './routes/api/inpocasi-stations'
import { Route as ApiMarineRouteImport } from './routes/api/marine'
import { Route as ApiMeteoamRouteImport } from './routes/api/meteoam'
import { Route as ApiMeteosourceRouteImport } from './routes/api/meteosource'
import { Route as ApiMeteostatRouteImport } from './routes/api/meteostat'
import { Route as ApiNetatmoRouteImport } from './routes/api/netatmo'
import { Route as ApiNwsRouteImport } from './routes/api/nws'
import { Route as ApiOpenmeteoProxyRouteImport } from './routes/api/openmeteo-proxy'
import { Route as ApiOpenweathermapRouteImport } from './routes/api/openweathermap'
import { Route as ApiPirateweatherRouteImport } from './routes/api/pirateweather'
import { Route as ApiPlaceImageRouteImport } from './routes/api/place-image'
import { Route as ApiPocasiczRouteImport } from './routes/api/pocasicz'
import { Route as ApiRainviewerRouteImport } from './routes/api/rainviewer'
import { Route as ApiShmuRouteImport } from './routes/api/shmu'
import { Route as ApiSmhiRouteImport } from './routes/api/smhi'
import { Route as ApiTomorrowioRouteImport } from './routes/api/tomorrowio'
import { Route as ApiVisualcrossingRouteImport } from './routes/api/visualcrossing'
import { Route as ApiWarningsRouteImport } from './routes/api/warnings'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'
import { Route as ApiWeatherapiRouteImport } from './routes/api/weatherapi'
import { Route as ApiWeatherbitRouteImport } from './routes/api/weatherbit'
import { Route as ApiWeathercomRouteImport } from './routes/api/weathercom'
import { Route as ApiWttrRouteImport } from './routes/api/wttr'
import { Route as ApiWundergroundRouteImport } from './routes/api/wunderground'
import { Route as ApiXweatherRouteImport } from './routes/api/xweather'
import { Route as ApiYrRouteImport } from './routes/api/yr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HydroRoute = HydroRouteImport.update({
  id: '/hydro',
  path: '/hydro',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccuweatherRoute = ApiAccuweatherRouteImport.update({
  id: '/api/accuweather',
  path: '/api/accuweather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAladinRoute = ApiAladinRouteImport.update({
  id: '/api/aladin',
  path: '/api/aladin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAviationRoute = ApiAviationRouteImport.update({
  id: '/api/aviation',
  path: '/api/aviation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBmkgRoute = ApiBmkgRouteImport.update({
  id: '/api/bmkg',
  path: '/api/bmkg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChmiRoute = ApiChmiRouteImport.update({
  id: '/api/chmi',
  path: '/api/chmi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChmiAqiRoute = ApiChmiAqiRouteImport.update({
  id: '/api/chmi-aqi',
  path: '/api/chmi-aqi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChmiRadarRoute = ApiChmiRadarRouteImport.update({
  id: '/api/chmi-radar',
  path: '/api/chmi-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFmiRoute = ApiFmiRouteImport.update({
  id: '/api/fmi',
  path: '/api/fmi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeosphereRoute = ApiGeosphereRouteImport.update({
  id: '/api/geosphere',
  path: '/api/geosphere',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeRoute = ApiHomeRouteImport.update({
  id: '/api/home',
  path: '/api/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHydroRoute = ApiHydroRouteImport.update({
  id: '/api/hydro',
  path: '/api/hydro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImgwRoute = ApiImgwRouteImport.update({
  id: '/api/imgw',
  path: '/api/imgw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInpocasiStationsRoute = ApiInpocasiStationsRouteImport.update({
  id: '/api/inpocasi-stations',
  path: '/api/inpocasi-stations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarineRoute = ApiMarineRouteImport.update({
  id: '/api/marine',
  path: '/api/marine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeteoamRoute = ApiMeteoamRouteImport.update({
  id: '/api/meteoam',
  path: '/api/meteoam',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeteosourceRoute = ApiMeteosourceRouteImport.update({
  id: '/api/meteosource',
  path: '/api/meteosource',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeteostatRoute = ApiMeteostatRouteImport.update({
  id: '/api/meteostat',
  path: '/api/meteostat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetatmoRoute = ApiNetatmoRouteImport.update({
  id: '/api/netatmo',
  path: '/api/netatmo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNwsRoute = ApiNwsRouteImport.update({
  id: '/api/nws',
  path: '/api/nws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenmeteoProxyRoute = ApiOpenmeteoProxyRouteImport.update({
  id: '/api/openmeteo-proxy',
  path: '/api/openmeteo-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenweathermapRoute = ApiOpenweathermapRouteImport.update({
  id: '/api/openweathermap',
  path: '/api/openweathermap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPirateweatherRoute = ApiPirateweatherRouteImport.update({
  id: '/api/pirateweather',
  path: '/api/pirateweather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaceImageRoute = ApiPlaceImageRouteImport.update({
  id: '/api/place-image',
  path: '/api/place-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPocasiczRoute = ApiPocasiczRouteImport.update({
  id: '/api/pocasicz',
  path: '/api/pocasicz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRainviewerRoute = ApiRainviewerRouteImport.update({
  id: '/api/rainviewer',
  path: '/api/rainviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShmuRoute = ApiShmuRouteImport.update({
  id: '/api/shmu',
  path: '/api/shmu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmhiRoute = ApiSmhiRouteImport.update({
  id: '/api/smhi',
  path: '/api/smhi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTomorrowioRoute = ApiTomorrowioRouteImport.update({
  id: '/api/tomorrowio',
  path: '/api/tomorrowio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisualcrossingRoute = ApiVisualcrossingRouteImport.update({
  id: '/api/visualcrossing',
  path: '/api/visualcrossing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarningsRoute = ApiWarningsRouteImport.update({
  id: '/api/warnings',
  path: '/api/warnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherapiRoute = ApiWeatherapiRouteImport.update({
  id: '/api/weatherapi',
  path: '/api/weatherapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherbitRoute = ApiWeatherbitRouteImport.update({
  id: '/api/weatherbit',
  path: '/api/weatherbit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeathercomRoute = ApiWeathercomRouteImport.update({
  id: '/api/weathercom',
  path: '/api/weathercom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWttrRoute = ApiWttrRouteImport.update({
  id: '/api/wttr',
  path: '/api/wttr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWundergroundRoute = ApiWundergroundRouteImport.update({
  id: '/api/wunderground',
  path: '/api/wunderground',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXweatherRoute = ApiXweatherRouteImport.update({
  id: '/api/xweather',
  path: '/api/xweather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYrRoute = ApiYrRouteImport.update({
  id: '/api/yr',
  path: '/api/yr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hydro': typeof HydroRoute
  '/radar': typeof RadarRoute
  '/settings': typeof SettingsRoute
  '/api/accuweather': typeof ApiAccuweatherRoute
  '/api/aladin': typeof ApiAladinRoute
  '/api/aviation': typeof ApiAviationRoute
  '/api/bmkg': typeof ApiBmkgRoute
  '/api/chmi': typeof ApiChmiRoute
  '/api/chmi-aqi': typeof ApiChmiAqiRoute
  '/api/chmi-radar': typeof ApiChmiRadarRoute
  '/api/fmi': typeof ApiFmiRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/geosphere': typeof ApiGeosphereRoute
  '/api/health': typeof ApiHealthRoute
  '/api/home': typeof ApiHomeRoute
  '/api/hydro': typeof ApiHydroRoute
  '/api/imgw': typeof ApiImgwRoute
  '/api/inpocasi-stations': typeof ApiInpocasiStationsRoute
  '/api/marine': typeof ApiMarineRoute
  '/api/meteoam': typeof ApiMeteoamRoute
  '/api/meteosource': typeof ApiMeteosourceRoute
  '/api/meteostat': typeof ApiMeteostatRoute
  '/api/netatmo': typeof ApiNetatmoRoute
  '/api/nws': typeof ApiNwsRoute
  '/api/openmeteo-proxy': typeof ApiOpenmeteoProxyRoute
  '/api/openweathermap': typeof ApiOpenweathermapRoute
  '/api/pirateweather': typeof ApiPirateweatherRoute
  '/api/place-image': typeof ApiPlaceImageRoute
  '/api/pocasicz': typeof ApiPocasiczRoute
  '/api/rainviewer': typeof ApiRainviewerRoute
  '/api/shmu': typeof ApiShmuRoute
  '/api/smhi': typeof ApiSmhiRoute
  '/api/tomorrowio': typeof ApiTomorrowioRoute
  '/api/visualcrossing': typeof ApiVisualcrossingRoute
  '/api/warnings': typeof ApiWarningsRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/weatherapi': typeof ApiWeatherapiRoute
  '/api/weatherbit': typeof ApiWeatherbitRoute
  '/api/weathercom': typeof ApiWeathercomRoute
  '/api/wttr': typeof ApiWttrRoute
  '/api/wunderground': typeof ApiWundergroundRoute
  '/api/xweather': typeof ApiXweatherRoute
  '/api/yr': typeof ApiYrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hydro': typeof HydroRoute
  '/radar': typeof RadarRoute
  '/settings': typeof SettingsRoute
  '/api/accuweather': typeof ApiAccuweatherRoute
  '/api/aladin': typeof ApiAladinRoute
  '/api/aviation': typeof ApiAviationRoute
  '/api/bmkg': typeof ApiBmkgRoute
  '/api/chmi': typeof ApiChmiRoute
  '/api/chmi-aqi': typeof ApiChmiAqiRoute
  '/api/chmi-radar': typeof ApiChmiRadarRoute
  '/api/fmi': typeof ApiFmiRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/geosphere': typeof ApiGeosphereRoute
  '/api/health': typeof ApiHealthRoute
  '/api/home': typeof ApiHomeRoute
  '/api/hydro': typeof ApiHydroRoute
  '/api/imgw': typeof ApiImgwRoute
  '/api/inpocasi-stations': typeof ApiInpocasiStationsRoute
  '/api/marine': typeof ApiMarineRoute
  '/api/meteoam': typeof ApiMeteoamRoute
  '/api/meteosource': typeof ApiMeteosourceRoute
  '/api/meteostat': typeof ApiMeteostatRoute
  '/api/netatmo': typeof ApiNetatmoRoute
  '/api/nws': typeof ApiNwsRoute
  '/api/openmeteo-proxy': typeof ApiOpenmeteoProxyRoute
  '/api/openweathermap': typeof ApiOpenweathermapRoute
  '/api/pirateweather': typeof ApiPirateweatherRoute
  '/api/place-image': typeof ApiPlaceImageRoute
  '/api/pocasicz': typeof ApiPocasiczRoute
  '/api/rainviewer': typeof ApiRainviewerRoute
  '/api/shmu': typeof ApiShmuRoute
  '/api/smhi': typeof ApiSmhiRoute
  '/api/tomorrowio': typeof ApiTomorrowioRoute
  '/api/visualcrossing': typeof ApiVisualcrossingRoute
  '/api/warnings': typeof ApiWarningsRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/weatherapi': typeof ApiWeatherapiRoute
  '/api/weatherbit': typeof ApiWeatherbitRoute
  '/api/weathercom': typeof ApiWeathercomRoute
  '/api/wttr': typeof ApiWttrRoute
  '/api/wunderground': typeof ApiWundergroundRoute
  '/api/xweather': typeof ApiXweatherRoute
  '/api/yr': typeof ApiYrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hydro': typeof HydroRoute
  '/radar': typeof RadarRoute
  '/settings': typeof SettingsRoute
  '/api/accuweather': typeof ApiAccuweatherRoute
  '/api/aladin': typeof ApiAladinRoute
  '/api/aviation': typeof ApiAviationRoute
  '/api/bmkg': typeof ApiBmkgRoute
  '/api/chmi': typeof ApiChmiRoute
  '/api/chmi-aqi': typeof ApiChmiAqiRoute
  '/api/chmi-radar': typeof ApiChmiRadarRoute
  '/api/fmi': typeof ApiFmiRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/geosphere': typeof ApiGeosphereRoute
  '/api/health': typeof ApiHealthRoute
  '/api/home': typeof ApiHomeRoute
  '/api/hydro': typeof ApiHydroRoute
  '/api/imgw': typeof ApiImgwRoute
  '/api/inpocasi-stations': typeof ApiInpocasiStationsRoute
  '/api/marine': typeof ApiMarineRoute
  '/api/meteoam': typeof ApiMeteoamRoute
  '/api/meteosource': typeof ApiMeteosourceRoute
  '/api/meteostat': typeof ApiMeteostatRoute
  '/api/netatmo': typeof ApiNetatmoRoute
  '/api/nws': typeof ApiNwsRoute
  '/api/openmeteo-proxy': typeof ApiOpenmeteoProxyRoute
  '/api/openweathermap': typeof ApiOpenweathermapRoute
  '/api/pirateweather': typeof ApiPirateweatherRoute
  '/api/place-image': typeof ApiPlaceImageRoute
  '/api/pocasicz': typeof ApiPocasiczRoute
  '/api/rainviewer': typeof ApiRainviewerRoute
  '/api/shmu': typeof ApiShmuRoute
  '/api/smhi': typeof ApiSmhiRoute
  '/api/tomorrowio': typeof ApiTomorrowioRoute
  '/api/visualcrossing': typeof ApiVisualcrossingRoute
  '/api/warnings': typeof ApiWarningsRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/weatherapi': typeof ApiWeatherapiRoute
  '/api/weatherbit': typeof ApiWeatherbitRoute
  '/api/weathercom': typeof ApiWeathercomRoute
  '/api/wttr': typeof ApiWttrRoute
  '/api/wunderground': typeof ApiWundergroundRoute
  '/api/xweather': typeof ApiXweatherRoute
  '/api/yr': typeof ApiYrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hydro'
    | '/radar'
    | '/settings'
    | '/api/accuweather'
    | '/api/aladin'
    | '/api/aviation'
    | '/api/bmkg'
    | '/api/chmi'
    | '/api/chmi-aqi'
    | '/api/chmi-radar'
    | '/api/fmi'
    | '/api/geocode'
    | '/api/geosphere'
    | '/api/health'
    | '/api/home'
    | '/api/hydro'
    | '/api/imgw'
    | '/api/inpocasi-stations'
    | '/api/marine'
    | '/api/meteoam'
    | '/api/meteosource'
    | '/api/meteostat'
    | '/api/netatmo'
    | '/api/nws'
    | '/api/openmeteo-proxy'
    | '/api/openweathermap'
    | '/api/pirateweather'
    | '/api/place-image'
    | '/api/pocasicz'
    | '/api/rainviewer'
    | '/api/shmu'
    | '/api/smhi'
    | '/api/tomorrowio'
    | '/api/visualcrossing'
    | '/api/warnings'
    | '/api/weather'
    | '/api/weatherapi'
    | '/api/weatherbit'
    | '/api/weathercom'
    | '/api/wttr'
    | '/api/wunderground'
    | '/api/xweather'
    | '/api/yr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hydro'
    | '/radar'
    | '/settings'
    | '/api/accuweather'
    | '/api/aladin'
    | '/api/aviation'
    | '/api/bmkg'
    | '/api/chmi'
    | '/api/chmi-aqi'
    | '/api/chmi-radar'
    | '/api/fmi'
    | '/api/geocode'
    | '/api/geosphere'
    | '/api/health'
    | '/api/home'
    | '/api/hydro'
    | '/api/imgw'
    | '/api/inpocasi-stations'
    | '/api/marine'
    | '/api/meteoam'
    | '/api/meteosource'
    | '/api/meteostat'
    | '/api/netatmo'
    | '/api/nws'
    | '/api/openmeteo-proxy'
    | '/api/openweathermap'
    | '/api/pirateweather'
    | '/api/place-image'
    | '/api/pocasicz'
    | '/api/rainviewer'
    | '/api/shmu'
    | '/api/smhi'
    | '/api/tomorrowio'
    | '/api/visualcrossing'
    | '/api/warnings'
    | '/api/weather'
    | '/api/weatherapi'
    | '/api/weatherbit'
    | '/api/weathercom'
    | '/api/wttr'
    | '/api/wunderground'
    | '/api/xweather'
    | '/api/yr'
  id:
    | '__root__'
    | '/'
    | '/hydro'
    | '/radar'
    | '/settings'
    | '/api/accuweather'
    | '/api/aladin'
    | '/api/aviation'
    | '/api/bmkg'
    | '/api/chmi'
    | '/api/chmi-aqi'
    | '/api/chmi-radar'
    | '/api/fmi'
    | '/api/geocode'
    | '/api/geosphere'
    | '/api/health'
    | '/api/home'
    | '/api/hydro'
    | '/api/imgw'
    | '/api/inpocasi-stations'
    | '/api/marine'
    | '/api/meteoam'
    | '/api/meteosource'
    | '/api/meteostat'
    | '/api/netatmo'
    | '/api/nws'
    | '/api/openmeteo-proxy'
    | '/api/openweathermap'
    | '/api/pirateweather'
    | '/api/place-image'
    | '/api/pocasicz'
    | '/api/rainviewer'
    | '/api/shmu'
    | '/api/smhi'
    | '/api/tomorrowio'
    | '/api/visualcrossing'
    | '/api/warnings'
    | '/api/weather'
    | '/api/weatherapi'
    | '/api/weatherbit'
    | '/api/weathercom'
    | '/api/wttr'
    | '/api/wunderground'
    | '/api/xweather'
    | '/api/yr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HydroRoute: typeof HydroRoute
  RadarRoute: typeof RadarRoute
  SettingsRoute: typeof SettingsRoute
  ApiAccuweatherRoute: typeof ApiAccuweatherRoute
  ApiAladinRoute: typeof ApiAladinRoute
  ApiAviationRoute: typeof ApiAviationRoute
  ApiBmkgRoute: typeof ApiBmkgRoute
  ApiChmiRoute: typeof ApiChmiRoute
  ApiChmiAqiRoute: typeof ApiChmiAqiRoute
  ApiChmiRadarRoute: typeof ApiChmiRadarRoute
  ApiFmiRoute: typeof ApiFmiRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiGeosphereRoute: typeof ApiGeosphereRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHomeRoute: typeof ApiHomeRoute
  ApiHydroRoute: typeof ApiHydroRoute
  ApiImgwRoute: typeof ApiImgwRoute
  ApiInpocasiStationsRoute: typeof ApiInpocasiStationsRoute
  ApiMarineRoute: typeof ApiMarineRoute
  ApiMeteoamRoute: typeof ApiMeteoamRoute
  ApiMeteosourceRoute: typeof ApiMeteosourceRoute
  ApiMeteostatRoute: typeof ApiMeteostatRoute
  ApiNetatmoRoute: typeof ApiNetatmoRoute
  ApiNwsRoute: typeof ApiNwsRoute
  ApiOpenmeteoProxyRoute: typeof ApiOpenmeteoProxyRoute
  ApiOpenweathermapRoute: typeof ApiOpenweathermapRoute
  ApiPirateweatherRoute: typeof ApiPirateweatherRoute
  ApiPlaceImageRoute: typeof ApiPlaceImageRoute
  ApiPocasiczRoute: typeof ApiPocasiczRoute
  ApiRainviewerRoute: typeof ApiRainviewerRoute
  ApiShmuRoute: typeof ApiShmuRoute
  ApiSmhiRoute: typeof ApiSmhiRoute
  ApiTomorrowioRoute: typeof ApiTomorrowioRoute
  ApiVisualcrossingRoute: typeof ApiVisualcrossingRoute
  ApiWarningsRoute: typeof ApiWarningsRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  ApiWeatherapiRoute: typeof ApiWeatherapiRoute
  ApiWeatherbitRoute: typeof ApiWeatherbitRoute
  ApiWeathercomRoute: typeof ApiWeathercomRoute
  ApiWttrRoute: typeof ApiWttrRoute
  ApiWundergroundRoute: typeof ApiWundergroundRoute
  ApiXweatherRoute: typeof ApiXweatherRoute
  ApiYrRoute: typeof ApiYrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hydro': {
      id: '/hydro'
      path: '/hydro'
      fullPath: '/hydro'
      preLoaderRoute: typeof HydroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accuweather': {
      id: '/api/accuweather'
      path: '/api/accuweather'
      fullPath: '/api/accuweather'
      preLoaderRoute: typeof ApiAccuweatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aladin': {
      id: '/api/aladin'
      path: '/api/aladin'
      fullPath: '/api/aladin'
      preLoaderRoute: typeof ApiAladinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aviation': {
      id: '/api/aviation'
      path: '/api/aviation'
      fullPath: '/api/aviation'
      preLoaderRoute: typeof ApiAviationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bmkg': {
      id: '/api/bmkg'
      path: '/api/bmkg'
      fullPath: '/api/bmkg'
      preLoaderRoute: typeof ApiBmkgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chmi': {
      id: '/api/chmi'
      path: '/api/chmi'
      fullPath: '/api/chmi'
      preLoaderRoute: typeof ApiChmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chmi-aqi': {
      id: '/api/chmi-aqi'
      path: '/api/chmi-aqi'
      fullPath: '/api/chmi-aqi'
      preLoaderRoute: typeof ApiChmiAqiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chmi-radar': {
      id: '/api/chmi-radar'
      path: '/api/chmi-radar'
      fullPath: '/api/chmi-radar'
      preLoaderRoute: typeof ApiChmiRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fmi': {
      id: '/api/fmi'
      path: '/api/fmi'
      fullPath: '/api/fmi'
      preLoaderRoute: typeof ApiFmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geosphere': {
      id: '/api/geosphere'
      path: '/api/geosphere'
      fullPath: '/api/geosphere'
      preLoaderRoute: typeof ApiGeosphereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/home': {
      id: '/api/home'
      path: '/api/home'
      fullPath: '/api/home'
      preLoaderRoute: typeof ApiHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hydro': {
      id: '/api/hydro'
      path: '/api/hydro'
      fullPath: '/api/hydro'
      preLoaderRoute: typeof ApiHydroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imgw': {
      id: '/api/imgw'
      path: '/api/imgw'
      fullPath: '/api/imgw'
      preLoaderRoute: typeof ApiImgwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inpocasi-stations': {
      id: '/api/inpocasi-stations'
      path: '/api/inpocasi-stations'
      fullPath: '/api/inpocasi-stations'
      preLoaderRoute: typeof ApiInpocasiStationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marine': {
      id: '/api/marine'
      path: '/api/marine'
      fullPath: '/api/marine'
      preLoaderRoute: typeof ApiMarineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meteoam': {
      id: '/api/meteoam'
      path: '/api/meteoam'
      fullPath: '/api/meteoam'
      preLoaderRoute: typeof ApiMeteoamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meteosource': {
      id: '/api/meteosource'
      path: '/api/meteosource'
      fullPath: '/api/meteosource'
      preLoaderRoute: typeof ApiMeteosourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meteostat': {
      id: '/api/meteostat'
      path: '/api/meteostat'
      fullPath: '/api/meteostat'
      preLoaderRoute: typeof ApiMeteostatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/netatmo': {
      id: '/api/netatmo'
      path: '/api/netatmo'
      fullPath: '/api/netatmo'
      preLoaderRoute: typeof ApiNetatmoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nws': {
      id: '/api/nws'
      path: '/api/nws'
      fullPath: '/api/nws'
      preLoaderRoute: typeof ApiNwsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openmeteo-proxy': {
      id: '/api/openmeteo-proxy'
      path: '/api/openmeteo-proxy'
      fullPath: '/api/openmeteo-proxy'
      preLoaderRoute: typeof ApiOpenmeteoProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openweathermap': {
      id: '/api/openweathermap'
      path: '/api/openweathermap'
      fullPath: '/api/openweathermap'
      preLoaderRoute: typeof ApiOpenweathermapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pirateweather': {
      id: '/api/pirateweather'
      path: '/api/pirateweather'
      fullPath: '/api/pirateweather'
      preLoaderRoute: typeof ApiPirateweatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/place-image': {
      id: '/api/place-image'
      path: '/api/place-image'
      fullPath: '/api/place-image'
      preLoaderRoute: typeof ApiPlaceImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pocasicz': {
      id: '/api/pocasicz'
      path: '/api/pocasicz'
      fullPath: '/api/pocasicz'
      preLoaderRoute: typeof ApiPocasiczRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rainviewer': {
      id: '/api/rainviewer'
      path: '/api/rainviewer'
      fullPath: '/api/rainviewer'
      preLoaderRoute: typeof ApiRainviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shmu': {
      id: '/api/shmu'
      path: '/api/shmu'
      fullPath: '/api/shmu'
      preLoaderRoute: typeof ApiShmuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smhi': {
      id: '/api/smhi'
      path: '/api/smhi'
      fullPath: '/api/smhi'
      preLoaderRoute: typeof ApiSmhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tomorrowio': {
      id: '/api/tomorrowio'
      path: '/api/tomorrowio'
      fullPath: '/api/tomorrowio'
      preLoaderRoute: typeof ApiTomorrowioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visualcrossing': {
      id: '/api/visualcrossing'
      path: '/api/visualcrossing'
      fullPath: '/api/visualcrossing'
      preLoaderRoute: typeof ApiVisualcrossingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warnings': {
      id: '/api/warnings'
      path: '/api/warnings'
      fullPath: '/api/warnings'
      preLoaderRoute: typeof ApiWarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weatherapi': {
      id: '/api/weatherapi'
      path: '/api/weatherapi'
      fullPath: '/api/weatherapi'
      preLoaderRoute: typeof ApiWeatherapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weatherbit': {
      id: '/api/weatherbit'
      path: '/api/weatherbit'
      fullPath: '/api/weatherbit'
      preLoaderRoute: typeof ApiWeatherbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weathercom': {
      id: '/api/weathercom'
      path: '/api/weathercom'
      fullPath: '/api/weathercom'
      preLoaderRoute: typeof ApiWeathercomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wttr': {
      id: '/api/wttr'
      path: '/api/wttr'
      fullPath: '/api/wttr'
      preLoaderRoute: typeof ApiWttrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wunderground': {
      id: '/api/wunderground'
      path: '/api/wunderground'
      fullPath: '/api/wunderground'
      preLoaderRoute: typeof ApiWundergroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xweather': {
      id: '/api/xweather'
      path: '/api/xweather'
      fullPath: '/api/xweather'
      preLoaderRoute: typeof ApiXweatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yr': {
      id: '/api/yr'
      path: '/api/yr'
      fullPath: '/api/yr'
      preLoaderRoute: typeof ApiYrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HydroRoute: HydroRoute,
  RadarRoute: RadarRoute,
  SettingsRoute: SettingsRoute,
  ApiAccuweatherRoute: ApiAccuweatherRoute,
  ApiAladinRoute: ApiAladinRoute,
  ApiAviationRoute: ApiAviationRoute,
  ApiBmkgRoute: ApiBmkgRoute,
  ApiChmiRoute: ApiChmiRoute,
  ApiChmiAqiRoute: ApiChmiAqiRoute,
  ApiChmiRadarRoute: ApiChmiRadarRoute,
  ApiFmiRoute: ApiFmiRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiGeosphereRoute: ApiGeosphereRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHomeRoute: ApiHomeRoute,
  ApiHydroRoute: ApiHydroRoute,
  ApiImgwRoute: ApiImgwRoute,
  ApiInpocasiStationsRoute: ApiInpocasiStationsRoute,
  ApiMarineRoute: ApiMarineRoute,
  ApiMeteoamRoute: ApiMeteoamRoute,
  ApiMeteosourceRoute: ApiMeteosourceRoute,
  ApiMeteostatRoute: ApiMeteostatRoute,
  ApiNetatmoRoute: ApiNetatmoRoute,
  ApiNwsRoute: ApiNwsRoute,
  ApiOpenmeteoProxyRoute: ApiOpenmeteoProxyRoute,
  ApiOpenweathermapRoute: ApiOpenweathermapRoute,
  ApiPirateweatherRoute: ApiPirateweatherRoute,
  ApiPlaceImageRoute: ApiPlaceImageRoute,
  ApiPocasiczRoute: ApiPocasiczRoute,
  ApiRainviewerRoute: ApiRainviewerRoute,
  ApiShmuRoute: ApiShmuRoute,
  ApiSmhiRoute: ApiSmhiRoute,
  ApiTomorrowioRoute: ApiTomorrowioRoute,
  ApiVisualcrossingRoute: ApiVisualcrossingRoute,
  ApiWarningsRoute: ApiWarningsRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  ApiWeatherapiRoute: ApiWeatherapiRoute,
  ApiWeatherbitRoute: ApiWeatherbitRoute,
  ApiWeathercomRoute: ApiWeathercomRoute,
  ApiWttrRoute: ApiWttrRoute,
  ApiWundergroundRoute: ApiWundergroundRoute,
  ApiXweatherRoute: ApiXweatherRoute,
  ApiYrRoute: ApiYrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
